[build]
  # Build command
  command = "npm ci --legacy-peer-deps --silent && npm run build"
  
  # Publish directory
  publish = "build"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js options for build performance
  NODE_OPTIONS = "--max_old_space_size=4096"
  
  # Enable React app environment variables
  REACT_APP_API_URL = "https://disruptorsmediav3.netlify.app"
  REACT_APP_NETLIFY = "true"
  REACT_APP_DEPLOYMENT_PLATFORM = "netlify"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for API endpoints (Netlify Functions)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Cache-Control = "no-cache"

# Redirects for SPA routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Function-specific configurations
[functions]
  # Global function settings
  node_bundler = "esbuild"
  
  # Individual function settings
  [functions."blog-posts"]
    timeout = 30
    memory = 1024
  
  [functions."google-docs-content"]
    timeout = 30
    memory = 1024
  
  [functions."ai-chat"]
    timeout = 30
    memory = 512
  
  [functions."contact-form"]
    timeout = 10
    memory = 256
  
  [functions."validate-image"]
    timeout = 15
    memory = 256
  
  [functions."health-check"]
    timeout = 10
    memory = 256

# Environment-specific settings
[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_NETLIFY = "true"
  REACT_APP_DEPLOYMENT_PLATFORM = "netlify"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  REACT_APP_NETLIFY = "true"
  REACT_APP_DEPLOYMENT_PLATFORM = "netlify"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  REACT_APP_NETLIFY = "true" 
  REACT_APP_DEPLOYMENT_PLATFORM = "netlify"